(function(){function t(n){return function(){return this[n]}}
(function(n){function g(d,b,c){for(var a=0;a<b.length;a++)b[a]="weswit/"+b[a].replace(w,"");n("weswit/"+d,b,c)}var w=/^.\//;g("utility-toolkit",[],function(){return"0.8.4"});g("IllegalStateException",[],function(){function d(b){this.name="IllegalStateException";this.message=b}d.prototype={toString:function(){return["[",this.name,this.message,"]"].join("|")}};return d});g("Environment",["./IllegalStateException"],function(d){var b="undefined"!==typeof window&&navigator&&document,c="undefined"!==typeof importScripts,
a="object"==typeof process&&(/node(\.exe)?$/.test(process.Za)||process.cb&&process.fb);if(b&&!document.getElementById)throw new d("Not supported browser");var f={g:function(){return b},K:function(){return!a&&(b||c)},ba:function(){return!b&&a},fa:function(){return!b&&!a&&c},va:function(){if(!this.g())throw new d("Trying to load a browser-only module on non-browser environment");}};f.isBrowserDocument=f.g;f.isBrowser=f.K;f.isNodeJS=f.ba;f.isWebWorker=f.fa;f.browserDocumentOrDie=f.va;return f});g("BrowserDetection",
["./Environment"],function(d){function b(e){var a=m;return function(){null===a&&(a=-1<q.indexOf(e));return a}}function c(e){var a=m;return function(){if(null===a){a=!0;for(var c=0;c<e.length;c++)a=a&&e[c]()}return a}}function a(e,a){var c=m,b=m;return function(d,f){null===c&&(b=(c=e())?a():null);return c?d&&b?!0===f?b<=d:!1===f?b>=d:b==d:!0:!1}}function f(e){return function(){var a=e.exec(q);return a&&2<=a.length?a[1]:null}}function e(e){return function(){return!e()}}var m=d.K()?null:!1,q=d.K()?navigator.userAgent.toLowerCase():
null,p=m;d={ea:b("rekonq"),L:b("chrome/"),ca:b("webkit"),Oa:b("playstation 3"),Ia:function(){null===p&&(p=document.childNodes&&!document.all&&!navigator.eb&&!navigator.Ya);return p},Ma:a(b("konqueror"),f(RegExp("konqueror/([0-9.]+)","g"))),La:a(b("msie"),f(RegExp("msie\\s([0-9]+)[.;]","g"))),Ka:a(b("firefox"),f(/Firefox\/(\d+\.?\d*)/)),v:a(function(){return"undefined"!=typeof opera},function(){if(opera.version){var e=opera.version(),e=e.replace(RegExp("[^0-9.]+","g"),"");return parseInt(e)}return 7})};
d.da=c([b("android"),d.ca,e(d.L)]);d.Na=c([d.v,b("opera mobi")]);d.Ja=c([b("safari"),function(e){var a=m;return function(){if(null===a){a=!1;for(var c=0;c<e.length;c++)a=a||e[c]()}return a}}([b("ipad"),b("iphone"),b("ipod"),c([e(d.da),e(d.L),e(d.ea)])])]);d.isProbablyRekonq=d.ea;d.isProbablyChrome=d.L;d.isProbablyAWebkit=d.ca;d.isProbablyPlaystation=d.Oa;d.isProbablyAndroidBrowser=d.da;d.isProbablyOperaMobile=d.Na;d.isProbablyApple=d.Ja;d.isProbablyAKhtml=d.Ia;d.isProbablyKonqueror=d.Ma;d.isProbablyIE=
d.La;d.isProbablyFX=d.Ka;d.isProbablyOldOpera=d.v;return d});g("Helpers",["./Environment"],function(d){var b=/^\s*([\s\S]*?)\s*$/,c=/,/,a=/\./,f={I:function(){return(new Date).getTime()},ja:function(e){return Math.round(Math.random()*(e||1E3))},trim:function(e){return e.replace(b,"$1")},Fa:function(e,b){if(e){if(!e.replace)return e;b?(e=e.replace(a,""),e=e.replace(c,".")):e=e.replace(c,"");return new Number(e)}return 0},isArray:function(e){return e.join&&"function"==typeof e.join},i:function(e,a,
c){if(!d.g())return!1;"undefined"!=typeof e.addEventListener?e.addEventListener(a,c,!1):"undefined"!=typeof e.attachEvent&&e.attachEvent("on"+a,c);return!0}};f.getTimeStamp=f.I;f.randomG=f.ja;f.trim=f.trim;f.getNumber=f.Fa;f.isArray=f.isArray;f.addEvent=f.i;return f});g("CookieManager",["./Helpers","./Environment"],function(d,b){var c=!1,a={l:function(){return c},W:function(){return this.l()?document.cookie.toString():null},na:function(a,e){this.oa(a,e,"")},oa:function(a,e,c){this.l()&&(document.cookie=
encodeURIComponent(a)+"\x3d"+e+"; "+c+"path\x3d/;")},P:function(a){if(!this.l())return null;a=encodeURIComponent(a)+"\x3d";for(var e=this.W(),e=e.split(";"),c=0;c<e.length;c++)if(e[c]=d.trim(e[c]),0==e[c].indexOf(a))return e[c].substring(a.length,e[c].length);return null},ka:function(a){if(this.l()){var e=new Date;e.setTime(e.getTime()-864E5);this.oa(a,"deleting","expires\x3d"+e.toGMTString()+"; ")}},wa:function(){if(b.g()&&"file:"!=document.location.protocol){c=!0;var a="LS__cookie_test"+d.ja();
this.na(a,"testing");var e=this.P(a);if("testing"==e&&(this.ka(a),e=this.P(a),null==e))return;c=!1}}};a.wa();a.areCookiesEnabled=a.l;a.getAllCookiesAsSingleString=a.W;a.writeCookie=a.na;a.removeCookie=a.ka;a.readCookie=a.P;return a});g("List",[],function(){function d(){this.data=[]}d.prototype={add:function(b){this.data.push(b)},remove:function(b){for(var c=0;c<this.data.length;c++)if(this.data[c]==b)return this.data.splice(c,1),!0;return!1},forEach:function(b){for(var c=0;c<this.data.length;c++)b(this.data[c])},
C:function(){return[].concat(this.data)},t:function(){this.data=[]}};d.prototype.add=d.prototype.add;d.prototype.remove=d.prototype.remove;d.prototype.forEach=d.prototype.forEach;d.prototype.asArray=d.prototype.C;d.prototype.clean=d.prototype.t;return d});g("EnvironmentStatus",["./Helpers","./BrowserDetection","./Environment","./List"],function(d,b,c,a){function f(a,e,c,b,d){return function(){a[e]||(a[c]=!0,b.forEach(function(a){try{if(a[d])a[d]();else a()}catch(e){}}),"preunloading"!=e&&b.t(),a[e]=
!0,a[c]=!1)}}function e(a,e){setTimeout(function(){if(a[e])a[e]();else a()},0)}function m(a,e,c,b){setTimeout(function(){c?b?a.apply(c,b):a.apply(c):b?a.apply(null,b):a()},e)}function q(){r=!0}var p=new a,g=new a,l=new a,r=!1,s={n:"onloadDone",ha:"onloadInprogress",r:"unloaded",S:"unloading",ia:"preunloading"};a={};for(var h in s)a[s[h]]=h;h={n:!1,ha:!1,r:!1,S:!1,ia:!1,$a:t("n"),ab:t("r"),bb:t("S"),ra:function(a){this.Ga()?g.add(a):e(a,"onloadEvent")},sa:function(a){this.Ha()?p.add(a):e(a,"unloadEvent")},
qa:function(a){l.add(a);this.ia&&e(a,"preUnloadEvent")},Sa:function(a){g.remove(a)},Ua:function(a){p.remove(a)},Ra:function(a){l.remove(a)},Ga:function(){return!(this.n||this.ha)},Ha:function(){return!(this.r||this.S)},ta:function(){d.i(window,"unload",this.xa);d.i(window,"beforeunload",this.ua);if(document&&"undefined"!=typeof document.readyState){if("COMPLETE"==document.readyState.toUpperCase()){this.s();return}m(this.U,1E3,this)}else if(this.aa()){this.s();return}if(!d.i(window,"load",this.w))this.s();
else if(b.v()){var a=!1;b.v(9,!1)&&(a=!0,d.i(document,"DOMContentLoaded",q));m(this.T,1E3,this,[a])}},s:function(){m(this.w,0)},U:function(){this.n||("COMPLETE"==document.readyState.toUpperCase()?this.w():m(this.U,1E3,this))},T:function(a){this.n||(r||!a&&this.aa()?this.w():m(this.T,1E3,this,[a]))},aa:function(){return"undefined"!=typeof document.getElementsByTagName&&"undefined"!=typeof document.getElementById&&(null!=document.getElementsByTagName("body")[0]||null!=document.body)}};h.w=f(h,a.onloadDone,
a.onloadInprogress,g,"onloadEvent");h.xa=f(h,a.unloaded,a.unloading,p,"unloadEvent");h.ua=f(h,a.preunloading,a.preunloading,l,"preUnloadEvent");c.g()?h.ta():h.s();h.addOnloadHandler=h.ra;h.addUnloadHandler=h.sa;h.addBeforeUnloadHandler=h.qa;h.removeOnloadHandler=h.Sa;h.removeUnloadHandler=h.Ua;h.removeBeforeUnloadHandler=h.Ra;return h});g("Executor",["./Helpers","./EnvironmentStatus","./Environment"],function(d,b,c){function a(){}function f(a,e){return a.time===e.time?a.O-e.O:a.time-e.time}function e(){v=
!1;q()}function m(){h?clearInterval(h):c.g()&&"undefined"!=typeof postMessage?(a=function(){window.postMessage("Lightstreamer.run",u)},d.i(window,"message",function(a){("Lightstreamer.run"==a.data&&"*"==u||a.origin==u)&&e()},!0)):c.ba()&&("undefined"!=typeof process&&process.Pa)&&(a=function(){process.Pa(e)});h=setInterval(q,p)}function q(){if(b.r)clearInterval(h);else{r=d.I();if(0<l.length){g&&(l.sort(f),g=!1);for(var a;0<l.length&&l[0].time<=r&&!b.r;)a=l.shift(),a.b&&(k.m(a),a.step&&s.push(a))}for(0>=
l.length&&(n=0);0<s.length;)a=s.shift(),a.O=n++,k.c(a,a.step,!0)}}var p=50,g=!1,l=[],r=d.I(),s=[],h=null,n=0,u=c.g()&&"file:"!=document.location.protocol?document.location.protocol+"//"+document.location.hostname+(document.location.port?":"+document.location.port:""):"*",v=!1,k={toString:function(){return["[|Executor",p,l.length,"]"].join("|")},H:function(){return l.length},o:function(a,e,c){return{b:a,e:e||null,h:c||null,O:n++}},c:function(a,e,c){a.step=c?e:null;a.time=r+parseInt(e);if(isNaN(a.time))throw"Executor error time: "+
a.time;l.push(a);g=!0},B:function(a,e,c,b){return this.d(a,e,c,b,!0)},Q:function(a){a&&(a.b=null,a.step=null)},d:function(e,c,b,d,f){e=this.o(e,b,d);this.c(e,c,f);0!=c||v||(v=!0,a());return e},N:function(a,e,c){a.h[e]=c},M:function(a,e){a.h=e},F:function(a,e){a.time+=e;g=!0},m:function(a,e){try{var c=e||a.h;a.e?c?a.b.apply(a.e,c):a.b.apply(a.e):c?a.b.apply(null,c):a.b()}catch(b){}}};c.fa()?setTimeout(m,1):m();k.getQueueLength=k.H;k.packTask=k.o;k.addPackedTimedTask=k.c;k.addRepetitiveTask=k.B;k.stopRepetitiveTask=
k.Q;k.addTimedTask=k.d;k.modifyTaskParam=k.N;k.modifyAllTaskParams=k.M;k.delayTask=k.F;k.executeTask=k.m;return k});g("Dismissable",["./Executor"],function(d){function b(){this.$()}b.prototype={t:function(){},$:function(c){this.R=this.k=0;this.timeout=c||5E3},Xa:function(c){c==this.R&&0>=this.k&&this.clean()},za:function(){this.k--;0>=this.k&&d.d(this.Xa,this.timeout,this,[this.R])},Va:function(){this.R++;0>this.k&&(this.k=0);this.k++}};b.prototype.touch=b.prototype.Va;b.prototype.dismiss=b.prototype.za;
b.prototype.clean=b.prototype.t;b.prototype.initTouches=b.prototype.$;return b});g("Inheritance",[],function(){function d(c,a,b){if(a)return b?a.apply(c,b):a.apply(c)}var b={pa:function(c,a,d){for(var e in a.prototype)c.prototype[e]||(c.prototype[e]=a.prototype[e]);d||(c.prototype._super_=a,c.prototype._callSuperConstructor=b._callSuperConstructor,c.prototype._callSuperMethod=b._callSuperMethod)},_callSuperMethod:function(c,a,b){return d(this,c.prototype._super_.prototype[a],b)},_callSuperConstructor:function(c,
a){d(this,c.prototype._super_,a)}};return b.pa});g("Matrix",[],function(){function d(b){this.a=b||{}}d.prototype={J:function(b,c,a){this.a[c]||(this.a[c]={});this.a[c][a]=b},get:function(b,c){return this.a[b]&&"undefined"!=typeof this.a[b][c]?this.a[b][c]:null},u:function(b,c){if(this.a[b]){this.a[b][c]&&delete this.a[b][c];for(var a in this.a[b])return;delete this.a[b]}},insertRow:function(b,c){this.a[c]=b},Y:function(b){return this.a[b]?this.a[b]:null},D:function(b){this.a[b]&&delete this.a[b]},
Da:t("a")};d.prototype.insert=d.prototype.J;d.prototype.get=d.prototype.get;d.prototype.del=d.prototype.u;d.prototype.insertRow=d.prototype.insertRow;d.prototype.getRow=d.prototype.Y;d.prototype.delRow=d.prototype.D;d.prototype.getEntireMatrix=d.prototype.Da;return d});g("DoubleKeyMatrix",["./Inheritance","./Matrix"],function(d,b){function c(){this._callSuperConstructor(c);this.p={}}c.prototype={J:function(a,b,e){"undefined"==typeof this.p[e]&&(this.p[e]=b,this._callSuperMethod(c,"insert",[a,b,e]))},
u:function(a,b){this._callSuperMethod(c,"del",[a,b]);delete this.p[b]},ya:function(a){var c=this.p[a];"undefined"!=typeof c&&this.u(c,a)},D:function(a){var b=this.Y(a),e;for(e in b)delete this.p[e];this._callSuperMethod(c,"delRow",[a])}};c.prototype.insert=c.prototype.J;c.prototype.del=c.prototype.u;c.prototype.delReverse=c.prototype.ya;c.prototype.delRow=c.prototype.D;d(c,b);return c});g("IllegalArgumentException",[],function(){function d(b){this.name="IllegalArgumentException";this.message=b}d.prototype=
{toString:function(){return["[",this.name,this.message,"]"].join("|")}};return d});g("DoubleKeyMap",["./IllegalArgumentException"],function(d){function b(){this.map={};this.q={}}function c(a){return null!==a&&"undefined"!=typeof a}function a(a,b,d){var f=a[d];c(f)&&(delete a[d],delete b[f])}function f(a,c){for(var b in a)c(b,a[b])}b.prototype={set:function(a,b){var f=this.map,g=this.q;if(!c(a)||!c(b))throw new d("values can't be null nor missing");var n=f[a],l=g[b];c(n)?n!==b&&(c(l)?(f[l]=n,f[a]=
b,g[b]=a,g[n]=l):(delete g[f[a]],f[a]=b,g[b]=a)):c(l)?(delete f[g[b]],g[b]=a,f[a]=b):(f[a]=b,g[b]=a)},remove:function(e){a(this.map,this.q,e)},Ta:function(e){a(this.q,this.map,e)},get:function(a){return this.map[a]},X:function(a){return this.q[a]},Aa:function(a){return"undefined"!=typeof this.get(a)},Ba:function(a){return"undefined"!=typeof this.X(a)},forEach:function(a){f(this.map,a)},Ca:function(a){f(this.q,a)}};b.prototype.set=b.prototype.set;b.prototype.remove=b.prototype.remove;b.prototype.removeReverse=
b.prototype.Ta;b.prototype.get=b.prototype.get;b.prototype.getReverse=b.prototype.X;b.prototype.exist=b.prototype.Aa;b.prototype.existReverse=b.prototype.Ba;b.prototype.forEach=b.prototype.forEach;b.prototype.forEachReverse=b.prototype.Ca;return b});g("EventDispatcher",["./Executor","./List","./Inheritance"],function(d,b,c){function a(){this._callSuperConstructor(a)}function f(){this.Z()}f.prototype={Z:function(){this.A=new a;this.ma=!1},addListener:function(a){a&&(a={f:a,ga:!0},this.A.add(a),this.G("onListenStart",
[this],a,!0))},removeListener:function(a){a&&(a=this.A.remove(a))&&this.G("onListenEnd",[this],a,!0)},Ea:function(){return this.A.C()},Wa:function(a){this.ma=!0===a},G:function(a,c,b,f){this.ma?this.V(a,c,b,!0):d.d(this.V,0,this,[a,c,b,f])},V:function(a,c,b,d){if(b&&b.f[a]&&(d||b.ga))try{c?b.f[a].apply(b.f,c):b.f[a].apply(b.f)}catch(f){}},dispatchEvent:function(a,b){var c=this;this.A.forEach(function(d){c.G(a,b,d,!1)})}};f.prototype.initDispatcher=f.prototype.Z;f.prototype.addListener=f.prototype.addListener;
f.prototype.removeListener=f.prototype.removeListener;f.prototype.getListeners=f.prototype.Ea;f.prototype.useSynchEvents=f.prototype.Wa;f.prototype.dispatchEvent=f.prototype.dispatchEvent;a.prototype={remove:function(a){for(var b=0;b<this.data.length;b++)if(this.data[b].f==a)return a=this.data[b],a.ga=!1,this.data.splice(b,1),a;return!1},C:function(){var a=[];this.forEach(function(b){a.push(b.f)});return a}};c(a,b);return f});g("ExecutorSimple",[],function(){function d(a){return function(){a.j?(a.time=
a.j,a.j=0,c.c(a,a.time,!1)):(c.m(a),a.la||b--)}}var b=0,c={toString:function(){return"[|ExecutorSimple|]"},H:function(){return b},o:function(a,b,c){return{b:a,e:b||null,h:c||null}},c:function(a,c,e){a.time=c;if(isNaN(a.time))throw"ExecutorSimple error time: "+a.time;a.la=e;b++;a.Qa=e?setInterval(d(a),a.time):setTimeout(d(a),a.time)},B:function(a,b,c,d){return this.d(a,b,c,d,!0)},Q:function(a){a&&(clearInterval(a.Qa),b--)},d:function(a,b,c,d,g){a=this.o(a,c,d);this.c(a,b,g);return a},N:function(a,
b,c){a.h[b]=c},M:function(a,b){a.h=b},F:function(a,b){if(a.la)throw"Can't delay repetitive tasks";a.j||(a.j=0);a.j+=b},m:function(a,b){try{var c=b||a.h;a.e?c?a.b.apply(a.e,c):a.b.apply(a.e):c?a.b.apply(null,c):a.b()}catch(d){}}};c.getQueueLength=c.H;c.packTask=c.o;c.addPackedTimedTask=c.c;c.addRepetitiveTask=c.B;c.stopRepetitiveTask=c.Q;c.addTimedTask=c.d;c.modifyTaskParam=c.N;c.modifyAllTaskParams=c.M;c.delayTask=c.F;c.executeTask=c.m;return c});g("Setter",["./IllegalArgumentException"],function(d){function b(){}
b.prototype.checkPositiveNumber=function(b,a,f){var e=new Number(b);if(isNaN(e))throw new d("The given value is not valid. Use a number");if(!f&&e!=Math.round(e))throw new d("The given value is not valid. Use an integer");if(a){if(0>b)throw new d("The given value is not valid. Use a positive number or 0");}else if(0>=b)throw new d("The given value is not valid. Use a positive number");return e};b.prototype.checkBool=function(b,a){if(!0===b||!1===b||a&&!b)return!0===b;throw new d("The given value is not valid. Use true or false");
};return b})})(define);}());
//# sourceMappingURL=utility-toolkit.js.map