(function(){(function(l){function h(e,a,d){for(var b=0;b<a.length;b++)a[b]="weswit/"+a[b].replace(m,"");l("weswit/"+e,a,d)}var m=/^.\//;h("utility-logging",[],function(){return"0.9"});h("SimpleLogLevels",[],function(){var e={FATAL:5,ERROR:4,WARN:3,INFO:2,DEBUG:1},a={a:function(a){return e[a]||0}};a.priority=a.a;return a});h("SimpleLogAppender",["./SimpleLogLevels"],function(e){function a(a,b){this.F=e.a(a)?a:"INFO";this.L=b||"*";this.G=null}a.prototype={u:function(a){a&&(a.n&&a.M)&&(this.G=a)},log:function(){},
l:function(a,b,f,k){return a+" | "+b+" | "+k+" | "+f},h:function(){return this.F},t:function(a){this.F=a=e.a(a)?a:"INFO";null!=this.G&&this.G.M()},C:function(){return this.L},ka:function(a){this.L=a||"*"}};a.prototype.log=a.prototype.log;a.prototype.setLoggerProvider=a.prototype.u;a.prototype.composeLine=a.prototype.l;a.prototype.getLevel=a.prototype.h;a.prototype.setLevel=a.prototype.t;a.prototype.getCategoryFilter=a.prototype.C;a.prototype.setCategoryFilter=a.prototype.ka;return a});h("BufferAppender",
["Inheritance","./SimpleLogAppender","./SimpleLogLevels"],function(e,a,d){function b(a,k,c){this._callSuperConstructor(b,[a,k]);this.N=!c||0>c?0:c;this.e=0;this.r=-1;this.buffer={}}b.prototype={reset:function(){this.e=0;this.r=-1;this.buffer={}},U:function(a){res=this.D(null,a);this.reset();return res},D:function(a,k,c){var b="";a?(a=this.r-a+1,a<this.e&&(a=this.e)):a=this.e;k=k||"\n";for(c=d.a(c||"DEBUG");a<=this.r;)d.a(this.buffer[a].$)>=c&&(b+=this.buffer[a].ga),b+=k,a++;return b},log:function(a,
b,c,d){var g=++this.r;0!=this.N&&g>=this.N&&(this.buffer[this.e]=null,this.e++);c=this.l(a,b,c,d);this.buffer[g]={$:b,ga:c}},W:function(){return this.r-this.e+1}};b.prototype.reset=b.prototype.reset;b.prototype.getLog=b.prototype.D;b.prototype.extractLog=b.prototype.U;b.prototype.log=b.prototype.log;b.prototype.getLength=b.prototype.W;e(b,a);return b});h("AlertAppender",["Inheritance","./SimpleLogAppender","./BufferAppender","Executor","Environment"],function(e,a,d,b,f){function k(a,b,f){this._callSuperConstructor(k,
[a,b]);this.K=!f||0>f?5:f;this.B=0;this.buffer=new d(a,b)}f.browserDocumentOrDie();k.prototype={na:function(a){alert(a)},log:function(a,f,k,e){this.B++;this.buffer.log(a,f,k,e);this.B>=this.K&&(this.B=0,b.addTimedTask(this.na,0,this,[this.buffer.D(this.K,"\n","",!1,this.F)]),this.buffer=new d)}};k.prototype.log=k.prototype.log;e(k,a);return k});h("ConsoleAppender",["Inheritance","./SimpleLogAppender","IllegalStateException"],function(e,a,d){function b(a,k){if("undefined"==typeof console)throw new d("This appender can't work if a console is not available. Enable the Browser console if possible or change appender.");
this._callSuperConstructor(b,[a,k])}b.prototype={log:function(a,b,c,d){c=this.l(a,b,c,d);switch(b){case "DEBUG":if(console.debug){console.debug(c);return}break;case "INFO":if(console.info){console.info(c);return}break;case "WARN":if(console.warn){console.warn(c);return}default:if(console.error){console.error(c);return}}console.log(c)}};b.prototype.log=b.prototype.log;e(b,a);return b});h("DOMAppender",["Inheritance","./SimpleLogAppender","IllegalArgumentException","Environment"],function(e,a,d,b){function f(a,
b,e){this._callSuperConstructor(f,[a,b]);if(!e)throw new d("a DOMElement instance is necessary for a DOMAppender to work.");this.d=e;this.R=this.H=!1}b.browserDocumentOrDie();f.prototype={ma:function(){this.R=!0===useInner},la:function(a){this.H=!0===a},log:function(a,b,f,d){a=this.l(a,b,f,d);this.R?this.d.innerHTML=this.H?a+"\x3cbr\x3e"+this.d.innerHTML:this.d.innerHTML+(a+"\x3cbr\x3e"):this.H?(a=document.createTextNode(a),b=document.createElement("br"),this.d.insertBefore(b,this.d.firstChild),this.d.insertBefore(a,
this.d.firstChild)):(a=document.createTextNode(a),b=document.createElement("br"),this.d.appendChild(a),this.d.appendChild(b))}};f.prototype.setUseInnerHtml=f.prototype.ma;f.prototype.setNextOnTop=f.prototype.la;f.prototype.log=f.prototype.log;e(f,a);return f});h("FunctionAppender",["Inheritance","./SimpleLogAppender"],function(e,a){function d(a,f,k,c){this._callSuperConstructor(d,[a,f]);this.V=k;this.ha=c||null}d.prototype={log:function(a,f,d,c){var e=this.V;if(e.apply){a=this.l(a,f,d,c);try{e.apply(this.ha,
[a])}catch(g){}}}};d.prototype.log=d.prototype.log;e(d,a);return d});h("LoggerProxy",["Helpers"],function(e){function a(a){this.J(a)}function d(){return!1}var b={error:d,warn:d,info:d,debug:d,fatal:d,isDebugEnabled:d,isInfoEnabled:d,isWarnEnabled:d,isErrorEnabled:d,isFatalEnabled:d};a.prototype={J:function(a){this.b=a||b},da:function(a){this.Y()&&(a+=this.f(arguments,1),this.m(a))},m:function(a,b){this.b.m(a,b)},Y:function(){return!this.b.p||this.b.p()},ba:function(a){this.P()&&(a+=this.f(arguments,
1),this.error(a))},ca:function(a,b){this.P()&&(b+=this.f(arguments,2),this.error(b,a))},error:function(a,b){this.b.error(a,b)},P:function(){return!this.b.o||this.b.o()},fa:function(a){this.Z()&&(a+=this.f(arguments,1),this.warn(a))},warn:function(a,b){this.b.warn(a,b)},Z:function(){return!this.b.q||this.b.q()},ea:function(a){this.Q()&&(a+=this.f(arguments,1),this.info(a))},info:function(a,b){this.b.info(a,b)},Q:function(){return!this.b.w||this.b.w()},aa:function(a){this.O()&&(a+=this.f(arguments,
1),this.debug(a))},debug:function(a,b){this.b.debug(a,b)},O:function(){return!this.b.v||this.b.v()},f:function(a,b){for(var c=" {",d=b?b:0;d<a.length;d++)try{var g=a[d];null===g?c+="NULL":0>g.length?c+="*":null!=g.charAt?c+=g:g.message?(c+=g.message,g.stack&&(c+="\n"+g.stack+"\n")):g[0]==g?c+=g:e.isArray(g)?(c+="(",c+=this.f(g),c+=")"):c+=g;c+=" "}catch(h){c+="missing-parameter "}return c+"}"}};a.prototype.debug=a.prototype.debug;a.prototype.isDebugLogEnabled=a.prototype.O;a.prototype.logDebug=a.prototype.aa;
a.prototype.info=a.prototype.info;a.prototype.isInfoLogEnabled=a.prototype.Q;a.prototype.logInfo=a.prototype.ea;a.prototype.warn=a.prototype.warn;a.prototype.isWarnEnabled=a.prototype.q;a.prototype.logWarn=a.prototype.fa;a.prototype.error=a.prototype.error;a.prototype.isErrorEnabled=a.prototype.o;a.prototype.logError=a.prototype.ba;a.prototype.logErrorExc=a.prototype.ca;a.prototype.fatal=a.prototype.m;a.prototype.isFatalEnabled=a.prototype.p;a.prototype.logFatal=a.prototype.da;return a});h("LoggerManager",
["./LoggerProxy","IllegalArgumentException"],function(e,a){var d={},b=null,f={u:function(f){if(f&&!f.n)throw new a("The given object is not a LoggerProvider");b=f;for(var c in d)b?d[c].J(b.n(c)):d[c].J(null)},X:function(a){d[a]||(d[a]=b?new e(b.n(a)):new e);return d[a]},ja:function(a){return a}};f.setLoggerProvider=f.u;f.getLoggerProxy=f.X;f.resolve=f.ja;return f});h("SimpleLogger",["./SimpleLogLevels"],function(e){function a(a,b){this.s=a;this.k=b;this.j="DEBUG"}a.prototype={m:function(a){this.p()&&
this.s.g(this.k,"FATAL",a)},p:function(){return e.a("FATAL")>=e.a(this.j)},error:function(a){this.o()&&this.s.g(this.k,"ERROR",a)},o:function(){return e.a("ERROR")>=e.a(this.j)},warn:function(a){this.q()&&this.s.g(this.k,"WARN",a)},q:function(){return e.a("WARN")>=e.a(this.j)},info:function(a){this.w()&&this.s.g(this.k,"INFO",a)},w:function(){return e.a("INFO")>=e.a(this.j)},debug:function(a){this.v()&&this.s.g(this.k,"DEBUG",a)},v:function(){return e.a("DEBUG")>=e.a(this.j)},t:function(a){this.j=
e.a(a)?a:"DEBUG"}};a.prototype.fatal=a.prototype.m;a.prototype.isFatalEnabled=a.prototype.p;a.prototype.error=a.prototype.error;a.prototype.isErrorEnabled=a.prototype.o;a.prototype.warn=a.prototype.warn;a.prototype.isWarnEnabled=a.prototype.q;a.prototype.info=a.prototype.info;a.prototype.isInfoEnabled=a.prototype.w;a.prototype.debug=a.prototype.debug;a.prototype.isDebugEnabled=a.prototype.v;a.prototype.setLevel=a.prototype.t;return a});h("SimpleLoggerProvider",["./SimpleLogger","./SimpleLogLevels"],
function(e,a){function d(){this.c=[];this.i={}}d.prototype={A:function(){var b=100,d=0;if(0<this.c.length){for(var e=0;e<this.c.length;e++)a.a(this.c[e].h())<b&&(b=a.a(this.c[e].h()),d=e);return this.c[d].h()}return null},I:function(a){for(var d in this.i)this.i[d].t(a)},T:function(a,d){var e=[];if("*"===a.C())return!0;for(var e=a.C().split(" "),c=0;c<e.length;c++)if(e[c]==d)return!0;return!1},S:function(a){a&&(a.log&&a.h)&&(this.c.push(a),a.u&&a.u(this));this.I(this.A())},ia:function(a){for(var d=
0;d<this.oa.length;d++)if(this.c[d]===a){this.c.splice(d,1);this.I(this.A());break}},M:function(){this.I(this.A())},n:function(a){this.i[a]||(this.i[a]=new e(this,a),0<this.c.length&&this.i[a].t(this.A()));return this.i[a]},g:function(b,d,e){var c;c="undefined"!=typeof window?window.name:"";var h=0,g=new Date,h=g.getHours();10>h&&(c+="0");c=c+h+":";h=g.getMinutes();10>h&&(c+="0");c+=h;c+=":";h=g.getSeconds();10>h&&(c+="0");c+=h;c+=",";c+=g.getMilliseconds();h=a.a(d);for(g=0;g<this.c.length;g++)a.a(this.c[g].h())<=
h&&this.T(this.c[g],b)&&this.c[g].log(b,d,e,c)}};d.prototype.addLoggerAppender=d.prototype.S;d.prototype.removeLoggerAppender=d.prototype.ia;d.prototype.getLogger=d.prototype.n;d.prototype.dispatchLog=d.prototype.g;return d})})(define);}());
//# sourceMappingURL=utility-logging.js.map