(function(){function t(q){return function(){return this[q]}}
(function(q){function g(d,c,f){for(var b=0;b<c.length;b++)c[b]="weswit/"+c[b].replace(w,"");q("weswit/"+d,c,f)}var w=/^.\//;g("utility-toolkit",[],function(){return"1.0"});g("IllegalStateException",[],function(){function d(c){this.name="IllegalStateException";this.message=c}d.prototype={toString:function(){return["[",this.name,this.message,"]"].join("|")}};return d});g("Environment",["./IllegalStateException"],function(d){var c="undefined"!==typeof window&&navigator&&document,f="undefined"!==typeof importScripts,
b="object"==typeof process&&(/node(\.exe)?$/.test(process.gb)||process.hb&&process.jb);if(c&&!document.getElementById)throw new d("Not supported browser");var e={c:function(){return c},K:function(){return!b&&(c||f)},ea:function(){return!c&&b},ia:function(){return!c&&!b&&f},ya:function(){if(!this.c())throw new d("Trying to load a browser-only module on non-browser environment");}};e.isBrowserDocument=e.c;e.isBrowser=e.K;e.isNodeJS=e.ea;e.isWebWorker=e.ia;e.browserDocumentOrDie=e.ya;return e});g("BrowserDetection",
["./Environment"],function(d){function c(a){var b=n;return function(){null===b&&(b=-1<p.indexOf(a));return b}}function f(a){var b=n;return function(){if(null===b){b=!0;for(var e=0;e<a.length;e++)b=b&&a[e]()}return b}}function b(a,b){var e=n,c=n;return function(d,f){null===e&&(c=(e=a())?b():null);return e?d&&c?!0===f?c<=d:!1===f?c>=d:c==d:!0:!1}}function e(a){return function(){var b=a.exec(p);return b&&2<=b.length?b[1]:null}}function a(a){return function(){return!a()}}var n=d.K()?null:!1,p=d.K()?navigator.userAgent.toLowerCase():
null,k=n;d={ha:c("rekonq"),M:c("chrome/"),L:c("webkit"),Ta:c("playstation 3"),Oa:function(){null===k&&(k=document.childNodes&&!document.all&&!navigator.ib&&!navigator.fb);return k},Ra:b(c("konqueror"),e(RegExp("konqueror/([0-9.]+)","g"))),ga:b(c("msie"),e(RegExp("msie\\s([0-9]+)[.;]","g"))),Qa:b(c("firefox"),e(/Firefox\/(\d+\.?\d*)/)),o:b(function(){return"undefined"!=typeof opera},function(){if(opera.version){var a=opera.version(),a=a.replace(RegExp("[^0-9.]+","g"),"");return parseInt(a)}return 7})};
d.fa=f([c("android"),d.L,a(d.M)]);d.Sa=f([d.o,c("opera mobi")]);d.Pa=f([c("safari"),function(a){var b=n;return function(){if(null===b){b=!1;for(var e=0;e<a.length;e++)b=b||a[e]()}return b}}([c("ipad"),c("iphone"),c("ipod"),f([a(d.fa),a(d.M),a(d.ha)])])]);d.isProbablyRekonq=d.ha;d.isProbablyChrome=d.M;d.isProbablyAWebkit=d.L;d.isProbablyPlaystation=d.Ta;d.isProbablyAndroidBrowser=d.fa;d.isProbablyOperaMobile=d.Sa;d.isProbablyApple=d.Pa;d.isProbablyAKhtml=d.Oa;d.isProbablyKonqueror=d.Ra;d.isProbablyIE=
d.ga;d.isProbablyFX=d.Qa;d.isProbablyOldOpera=d.o;return d});g("Helpers",["./Environment"],function(d){var c=/^\s*([\s\S]*?)\s*$/,f=/,/,b=/\./,e={I:function(){return(new Date).getTime()},ma:function(a){return Math.round(Math.random()*(a||1E3))},trim:function(a){return a.replace(c,"$1")},Ka:function(a,e){if(a){if(!a.replace)return a;e?(a=a.replace(b,""),a=a.replace(f,".")):a=a.replace(f,"");return new Number(a)}return 0},isArray:function(a){return a.join&&"function"==typeof a.join},i:function(a,b,
e){if(!d.c())return!1;"undefined"!=typeof a.addEventListener?a.addEventListener(b,e,!1):"undefined"!=typeof a.attachEvent&&a.attachEvent("on"+b,e);return!0}};e.getTimeStamp=e.I;e.randomG=e.ma;e.trim=e.trim;e.getNumber=e.Ka;e.isArray=e.isArray;e.addEvent=e.i;return e});g("CookieManager",["./Helpers","./Environment"],function(d,c){var f=!1,b={l:function(){return f},Z:function(){return this.l()?document.cookie.toString():null},ra:function(b,a){this.sa(b,a,"")},sa:function(b,a,c){this.l()&&(document.cookie=
encodeURIComponent(b)+"\x3d"+a+"; "+c+"path\x3d/;")},Q:function(b){if(!this.l())return null;b=encodeURIComponent(b)+"\x3d";for(var a=this.Z(),a=a.split(";"),c=0;c<a.length;c++)if(a[c]=d.trim(a[c]),0==a[c].indexOf(b))return a[c].substring(b.length,a[c].length);return null},na:function(b){if(this.l()){var a=new Date;a.setTime(a.getTime()-864E5);this.sa(b,"deleting","expires\x3d"+a.toGMTString()+"; ")}},za:function(){if(c.c()&&"file:"!=document.location.protocol){f=!0;var b="LS__cookie_test"+d.ma();
this.ra(b,"testing");var a=this.Q(b);if("testing"==a&&(this.na(b),a=this.Q(b),null==a))return;f=!1}}};b.za();b.areCookiesEnabled=b.l;b.getAllCookiesAsSingleString=b.Z;b.writeCookie=b.ra;b.removeCookie=b.na;b.readCookie=b.Q;return b});g("List",[],function(){function d(){this.data=[]}d.prototype={add:function(c){this.data.push(c)},remove:function(c){for(var d=0;d<this.data.length;d++)if(this.data[d]==c)return this.data.splice(d,1),!0;return!1},forEach:function(c){for(var d=0;d<this.data.length;d++)c(this.data[d])},
C:function(){return[].concat(this.data)},m:function(){this.data=[]}};d.prototype.add=d.prototype.add;d.prototype.remove=d.prototype.remove;d.prototype.forEach=d.prototype.forEach;d.prototype.asArray=d.prototype.C;d.prototype.clean=d.prototype.m;return d});g("EnvironmentStatus",["./Helpers","./BrowserDetection","./Environment","./List"],function(d,c,f,b){function e(a,b,c,d,e){return function(){a[b]||(a[c]=!0,d.forEach(function(a){try{if(a[e])a[e]();else a()}catch(b){}}),"preunloading"!=b&&d.m(),a[b]=
!0,a[c]=!1)}}function a(a,b){setTimeout(function(){if(a[b])a[b]();else a()},0)}function n(a,b,c,d){setTimeout(function(){c?d?a.apply(c,d):a.apply(c):d?a.apply(null,d):a()},b)}function p(){r=!0}var k=new b,m=new b,g=new b,r=!1,s={p:"onloadDone",ka:"onloadInprogress",t:"unloaded",T:"unloading",la:"preunloading"};b={};for(var h in s)b[s[h]]=h;h={p:!1,ka:!1,t:!1,T:!1,la:!1,La:t("p"),Ua:t("t"),Va:t("T"),va:function(b){this.Ma()?m.add(b):a(b,"onloadEvent")},U:function(b){this.Na()?k.add(b):a(b,"unloadEvent")},
ua:function(b){g.add(b);this.la&&a(b,"preUnloadEvent")},Za:function(a){m.remove(a)},ab:function(a){k.remove(a)},Ya:function(a){g.remove(a)},Ma:function(){return!(this.p||this.ka)},Na:function(){return!(this.t||this.T)},wa:function(){d.i(window,"unload",this.Aa);d.i(window,"beforeunload",this.xa);if(document&&"undefined"!=typeof document.readyState){if("COMPLETE"==document.readyState.toUpperCase()){this.u();return}n(this.W,1E3,this)}else if(this.da()){this.u();return}if(!d.i(window,"load",this.w))this.u();
else if(c.o()){var a=!1;c.o(9,!1)&&(a=!0,d.i(document,"DOMContentLoaded",p));n(this.V,1E3,this,[a])}},u:function(){n(this.w,0)},W:function(){this.p||("COMPLETE"==document.readyState.toUpperCase()?this.w():n(this.W,1E3,this))},V:function(a){this.p||(r||!a&&this.da()?this.w():n(this.V,1E3,this,[a]))},da:function(){return"undefined"!=typeof document.getElementsByTagName&&"undefined"!=typeof document.getElementById&&(null!=document.getElementsByTagName("body")[0]||null!=document.body)}};h.w=e(h,b.onloadDone,
b.onloadInprogress,m,"onloadEvent");h.Aa=e(h,b.unloaded,b.unloading,k,"unloadEvent");h.xa=e(h,b.preunloading,b.preunloading,g,"preUnloadEvent");f.c()?h.wa():h.u();h.addOnloadHandler=h.va;h.addUnloadHandler=h.U;h.addBeforeUnloadHandler=h.ua;h.removeOnloadHandler=h.Za;h.removeUnloadHandler=h.ab;h.removeBeforeUnloadHandler=h.Ya;h.isLoaded=h.La;h.isUnloaded=h.Ua;h.isUnloading=h.Va;return h});g("Executor",["./Helpers","./EnvironmentStatus","./Environment"],function(d,c,f){function b(){}function e(a,b){return a.time===
b.time?a.P-b.P:a.time-b.time}function a(){v=!1;p()}function n(){h?clearInterval(h):f.c()&&"undefined"!=typeof postMessage?(b=function(){window.postMessage("Lightstreamer.run",u)},d.i(window,"message",function(b){("Lightstreamer.run"==b.data&&"*"==u||b.origin==u)&&a()},!0)):f.ea()&&("undefined"!=typeof process&&process.Wa)&&(b=function(){process.Wa(a)});h=setInterval(p,k)}function p(){if(c.t)clearInterval(h);else{r=d.I();if(0<g.length){m&&(g.sort(e),m=!1);for(var a;0<g.length&&g[0].time<=r&&!c.t;)a=
g.shift(),a.b&&(l.n(a),a.step&&s.push(a))}for(0>=g.length&&(q=0);0<s.length;)a=s.shift(),a.P=q++,l.d(a,a.step,!0)}}var k=50,m=!1,g=[],r=d.I(),s=[],h=null,q=0,u=f.c()&&"file:"!=document.location.protocol?document.location.protocol+"//"+document.location.hostname+(document.location.port?":"+document.location.port:""):"*",v=!1,l={toString:function(){return["[|Executor",k,g.length,"]"].join("|")},H:function(){return g.length},q:function(a,b,c){return{b:a,f:b||null,h:c||null,P:q++}},d:function(a,b,c){a.step=
c?b:null;a.time=r+parseInt(b);if(isNaN(a.time))throw"Executor error time: "+a.time;g.push(a);m=!0},B:function(a,b,c,d){return this.e(a,b,c,d,!0)},R:function(a){a&&(a.b=null,a.step=null)},e:function(a,c,d,e,f){a=this.q(a,d,e);this.d(a,c,f);0!=c||v||(v=!0,b());return a},O:function(a,b,c){a.h[b]=c},N:function(a,b){a.h=b},F:function(a,b){a.time+=b;m=!0},n:function(a,b){try{var c=b||a.h;a.f?c?a.b.apply(a.f,c):a.b.apply(a.f):c?a.b.apply(null,c):a.b()}catch(d){}}};f.ia()?setTimeout(n,1):n();l.getQueueLength=
l.H;l.packTask=l.q;l.addPackedTimedTask=l.d;l.addRepetitiveTask=l.B;l.stopRepetitiveTask=l.R;l.addTimedTask=l.e;l.modifyTaskParam=l.O;l.modifyAllTaskParams=l.N;l.delayTask=l.F;l.executeTask=l.n;return l});g("Dismissable",["./Executor"],function(d){function c(){this.ca()}c.prototype={m:function(){},ca:function(c){this.S=this.k=0;this.timeout=c||5E3},eb:function(c){c==this.S&&0>=this.k&&this.m()},Ca:function(){this.k--;0>=this.k&&d.e(this.eb,this.timeout,this,[this.S])},bb:function(){this.S++;0>this.k&&
(this.k=0);this.k++}};c.prototype.touch=c.prototype.bb;c.prototype.dismiss=c.prototype.Ca;c.prototype.clean=c.prototype.m;c.prototype.initTouches=c.prototype.ca;return c});g("Inheritance",["./IllegalStateException"],function(d){function c(b,c,a){if(c)return a?c.apply(b,a):c.apply(b)}var f={ta:function(b,c,a,n){for(var p in c.prototype)if(!b.prototype[p])b.prototype[p]=c.prototype[p];else if(n){var k;a:{k=c.prototype;var g=void 0;for(g in k)if(k[p]==k[g]&&p!=g){k=g;break a}k=null}if(k){if(b.prototype[k]&&
b.prototype[k]!==b.prototype[p]&&c.prototype[k]!==c.prototype[k])throw new d("Can't solve alias collision, try to minify the classes again ("+k+", "+p+")");b.prototype[k]=b.prototype[p]}}a||(b.prototype._super_=c,b.prototype._callSuperConstructor=f._callSuperConstructor,b.prototype._callSuperMethod=f._callSuperMethod)},_callSuperMethod:function(b,d,a){return c(this,b.prototype._super_.prototype[d],a)},_callSuperConstructor:function(b,d){c(this,b.prototype._super_,d)}};return f.ta});g("Matrix",[],
function(){function d(c){this.a=c||{}}d.prototype={J:function(c,d,b){this.a[d]||(this.a[d]={});this.a[d][b]=c},get:function(c,d){return this.a[c]&&"undefined"!=typeof this.a[c][d]?this.a[c][d]:null},v:function(c,d){if(this.a[c]){this.a[c][d]&&delete this.a[c][d];for(var b in this.a[c])return;delete this.a[c]}},insertRow:function(c,d){this.a[d]=c},aa:function(c){return this.a[c]?this.a[c]:null},D:function(c){this.a[c]&&delete this.a[c]},Ha:t("a")};d.prototype.insert=d.prototype.J;d.prototype.get=d.prototype.get;
d.prototype.del=d.prototype.v;d.prototype.insertRow=d.prototype.insertRow;d.prototype.getRow=d.prototype.aa;d.prototype.delRow=d.prototype.D;d.prototype.getEntireMatrix=d.prototype.Ha;return d});g("DoubleKeyMatrix",["./Inheritance","./Matrix"],function(d,c){function f(){this._callSuperConstructor(f);this.r={}}f.prototype={J:function(b,c,a){"undefined"==typeof this.r[a]&&(this.r[a]=c,this._callSuperMethod(f,"insert",[b,c,a]))},v:function(b,c){this._callSuperMethod(f,"del",[b,c]);delete this.r[c]},
Ba:function(b){var c=this.r[b];"undefined"!=typeof c&&this.v(c,b)},D:function(b){var c=this.aa(b),a;for(a in c)delete this.r[a];this._callSuperMethod(f,"delRow",[b])}};f.prototype.insert=f.prototype.J;f.prototype.del=f.prototype.v;f.prototype.delReverse=f.prototype.Ba;f.prototype.delRow=f.prototype.D;d(f,c);return f});g("IllegalArgumentException",[],function(){function d(c){this.name="IllegalArgumentException";this.message=c}d.prototype={toString:function(){return["[",this.name,this.message,"]"].join("|")}};
return d});g("DoubleKeyMap",["./IllegalArgumentException"],function(d){function c(){this.map={};this.s={}}function f(a){return null!==a&&"undefined"!=typeof a}function b(a,b,c){var d=a[c];f(d)&&(delete a[c],delete b[d])}function e(a,b){for(var c in a)b(c,a[c])}c.prototype={set:function(a,b){var c=this.map,e=this.s;if(!f(a)||!f(b))throw new d("values can't be null nor missing");var g=c[a],q=e[b];f(g)?g!==b&&(f(q)?(c[q]=g,c[a]=b,e[b]=a,e[g]=q):(delete e[c[a]],c[a]=b,e[b]=a)):f(q)?(delete c[e[b]],e[b]=
a,c[a]=b):(c[a]=b,e[b]=a)},remove:function(a){b(this.map,this.s,a)},$a:function(a){b(this.s,this.map,a)},get:function(a){return this.map[a]},$:function(a){return this.s[a]},Ea:function(a){return"undefined"!=typeof this.get(a)},Fa:function(a){return"undefined"!=typeof this.$(a)},forEach:function(a){e(this.map,a)},Ga:function(a){e(this.s,a)}};c.prototype.set=c.prototype.set;c.prototype.remove=c.prototype.remove;c.prototype.removeReverse=c.prototype.$a;c.prototype.get=c.prototype.get;c.prototype.getReverse=
c.prototype.$;c.prototype.exist=c.prototype.Ea;c.prototype.existReverse=c.prototype.Fa;c.prototype.forEach=c.prototype.forEach;c.prototype.forEachReverse=c.prototype.Ga;return c});g("EventDispatcher",["./Executor","./List","./Inheritance"],function(d,c,f){function b(){this._callSuperConstructor(b)}function e(){this.ba()}e.prototype={ba:function(){this.A=new b;this.qa=!1},addListener:function(a){a&&(a={g:a,ja:!0},this.A.add(a),this.G("onListenStart",[this],a,!0))},removeListener:function(a){a&&(a=
this.A.remove(a))&&this.G("onListenEnd",[this],a,!0)},Ja:function(){return this.A.C()},cb:function(a){this.qa=!0===a},G:function(a,b,c,e){this.qa?this.Y(a,b,c,!0):d.e(this.Y,0,this,[a,b,c,e])},Y:function(a,b,c,d){if(c&&c.g[a]&&(d||c.ja))try{b?c.g[a].apply(c.g,b):c.g[a].apply(c.g)}catch(e){}},dispatchEvent:function(a,b){var c=this;this.A.forEach(function(d){c.G(a,b,d,!1)})}};e.prototype.initDispatcher=e.prototype.ba;e.prototype.addListener=e.prototype.addListener;e.prototype.removeListener=e.prototype.removeListener;
e.prototype.getListeners=e.prototype.Ja;e.prototype.useSynchEvents=e.prototype.cb;e.prototype.dispatchEvent=e.prototype.dispatchEvent;b.prototype={remove:function(a){for(var b=0;b<this.data.length;b++)if(this.data[b].g==a)return a=this.data[b],a.ja=!1,this.data.splice(b,1),a;return!1},C:function(){var a=[];this.forEach(function(b){a.push(b.g)});return a}};f(b,c);return e});g("ExecutorSimple",[],function(){function d(b){return function(){b.j?(b.time=b.j,b.j=0,f.d(b,b.time,!1)):(f.n(b),b.pa||c--)}}
var c=0,f={toString:function(){return"[|ExecutorSimple|]"},H:function(){return c},q:function(b,c,a){return{b:b,f:c||null,h:a||null}},d:function(b,e,a){b.time=e;if(isNaN(b.time))throw"ExecutorSimple error time: "+b.time;b.pa=a;c++;b.Xa=a?setInterval(d(b),b.time):setTimeout(d(b),b.time)},B:function(b,c,a,d){return this.e(b,c,a,d,!0)},R:function(b){b&&(clearInterval(b.Xa),c--)},e:function(b,c,a,d,f){b=this.q(b,a,d);this.d(b,c,f);return b},O:function(b,c,a){b.h[c]=a},N:function(b,c){b.h=c},F:function(b,
c){if(b.pa)throw"Can't delay repetitive tasks";b.j||(b.j=0);b.j+=c},n:function(b,c){try{var a=c||b.h;b.f?a?b.b.apply(b.f,a):b.b.apply(b.f):a?b.b.apply(null,a):b.b()}catch(d){}}};f.getQueueLength=f.H;f.packTask=f.q;f.addPackedTimedTask=f.d;f.addRepetitiveTask=f.B;f.stopRepetitiveTask=f.R;f.addTimedTask=f.e;f.modifyTaskParam=f.O;f.modifyAllTaskParams=f.N;f.delayTask=f.F;f.executeTask=f.n;return f});g("IFrameHandler",["./BrowserDetection","./EnvironmentStatus","./Environment"],function(d,c,f){var b=
d.L()?null:"about:blank",e={},a={X:function(a,c){if(!f.c())return null;var g=document.getElementsByTagName("BODY")[0];if(!g)return null;c=c||b;var m=document.createElement("iframe");m.style.visibility="hidden";m.style.height="0px";m.style.width="0px";m.style.display="none";m.name=a;m.id=a;d.ga()||d.o()?(m.src=c,g.appendChild(m)):(g.appendChild(m),m.src=c);try{if(m.contentWindow){try{m.contentWindow.name=a}catch(q){}e[a]=m.contentWindow;return e[a]}return document.frames&&document.frames[a]?(e[a]=
document.frames[a],e[a]):null}catch(r){return null}},Ia:function(a,b,c){b&&!e[a]&&this.X(a,c);return e[a]||null},Da:function(a){if(e[a]){try{document.getElementsByTagName("BODY")[0].removeChild(document.getElementById(a))}catch(b){}delete e[a]}},oa:function(){for(var a in e)try{document.getElementsByTagName("BODY")[0].removeChild(document.getElementById(a))}catch(b){}e={}}};a.createFrame=a.X;a.getFrameWindow=a.Ia;a.disposeFrame=a.Da;a.removeFrames=a.oa;c.U(a.oa);return a});g("Setter",["./IllegalArgumentException"],
function(d){function c(){}c.prototype.checkPositiveNumber=function(c,b,e){var a=new Number(c);if(isNaN(a))throw new d("The given value is not valid. Use a number");if(!e&&a!=Math.round(a))throw new d("The given value is not valid. Use an integer");if(b){if(0>c)throw new d("The given value is not valid. Use a positive number or 0");}else if(0>=c)throw new d("The given value is not valid. Use a positive number");return a};c.prototype.checkBool=function(c,b){if(!0===c||!1===c||b&&!c)return!0===c;throw new d("The given value is not valid. Use true or false");
};return c})})(define);}());
//# sourceMappingURL=utility-toolkit.js.map